### PR TITLE
Added actionlib in CMakeList to solve linking issue.

### PR DESCRIPTION
**Pull request by dg-shadow**

### CODE REVIEW

**Comment by dg-shadow** [comment]
Hmm, Travis is failing, but from the look of it not because of my change... Is this something to be expected or have I done something horrible?!? ;)

Thanks,
Dan

**Comment by gavanderhoorn** [comment]
@dg-shadow: no, this repository has just not been setup for Travis yet, but the organisation has, so that is why it's failing.

**Comment by dg-shadow** [comment]
Ah, ok, cool. In which case could this be merged?

**Comment by gavanderhoorn** [comment]
Probably. But I'm not the maintainer of this repository.

**Comment by dg-shadow** [comment]
Fair point ;)

**Comment by drchrislewis** [comment]
I think I am a maintainer, but obviously not a good one. +1 @dg-shadow  @gavanderhoorn

**Pull request merged**
